const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNE9jWmh1bDlHQmVaNnZpTi9Ta2pMN1pFR1FtdUpQZWNsY1Nld2dNQ09FZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYWNWL1Baa3NEUkk2NHhPNlFSZkZCL1Y4WWpHS1h3L3E4aTczYVlNcE9pYz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJZSVR3THExRHdLR3lGYVVKUGIzcjE4ODhwenQweS8xOUFNWjZydlJyV204PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI5L3hoOVRZNEdCeHJaYUVGUUZOcUp1TEtMK3p0MVB5RVZqTFBQQUtaUDNNPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImNPN01KT2R1VUh6eVVON0FheC8zWjNuSEo2d0FwU3dkRXZxbnFsY0sxM0k9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImdwUVZMS08wZG5ybjZNcEhrRjRCdUYrMVk3WGNXMk90OFZOR0R3amU4M289In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYUlIVWlsSlBKTTZPNzhwdlZIWjIzMWNqUERrZE42Vk1ZRExQZ3ExcDFFQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiejV6RFFsdUJDSGlGRHY5U3pPY0kxK1lPNEJHNXJHY25XQlh4NlMvRnlDRT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ijd6MC9lY3lHWThuR3VZdUp1clFuN1V5TG82NnZ4cVI0ekg4OFA5WlpuUTdkZk5yVG1YazA4cnRMK3dlalg1NTJtZzFTL2NXR3pWU0cwUXQ2RXVLUUR3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTU4LCJhZHZTZWNyZXRLZXkiOiJGQ0VyOXN0QjBvTWpuVm9hOGtJTldQdS9DM1JRNGJkK3BZTlErU0xUVEVFPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJLN01OVk5PVyIsIm1lIjp7ImlkIjoiOTIzMDI0MjI3NTc3OjUzQHMud2hhdHNhcHAubmV0IiwibmFtZSI6Ik11aGFtbWFkIE11YmVlbiIsImxpZCI6IjQ4Njk2NzkyMTg2OTk1OjUzQGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDT25KdFBRQkVMM09vTXdHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiOTdGTk4vM0lJVlc4K3QrVWl3aHVEYnhXbjNTS3UvUHZBbzlzV0dVWFptUT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiM0gwMWlsWVVVck1zNXYya0FFaVhkR0xqZW9id1M4UjNON3hIbUwySUVNTVBMVDVmUDdqdHZRbWZ3RUpKU2dEWmJEWGkvNGJwZXpVOXorOG42ZVQzQXc9PSIsImRldmljZVNpZ25hdHVyZSI6InJNckZrTHVJc09hMXRPQVZUbjYrZ1h0VnhhQTdicW9jUGNmeVkweFRIOEdqL0gxM0dWT1VBeTN1SkxDaVk1NUVTR3JYakxnNFRMWlNMRTc2a0F1VUJ3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiOTIzMDI0MjI3NTc3OjUzQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmZleFRUZjl5Q0ZWdlByZmxJc0liZzI4VnA5MGlydno3d0tQYkZobEYyWmsifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBVUlDQWdOIn0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc3MDUzMDYzMSwibGFzdFByb3BIYXNoIjoiMUs0aEg0IiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFERXkifQ==",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
